[package]
name = "red-flip"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
actix-cors = "0.7"
actix-web-actors = "4"
actix = "0.13"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

libsql = "0.9"

jsonwebtoken = "9"
bcrypt = "0.15"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
dotenvy = "0.15"
env_logger = "0.11"
log = "0.4"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
